### ISSUE TITLE
Add instructions for running make after cloning

### ISSUE THREAD

**Issue by fdesjardins** [stellar/soroban-examples#56]
### What problem does your feature solve?

Users should be able to run `make` after cloning the repository. I found I needed a few additional steps beyond the `Getting Started` instructions in the Soroban docs:

```console
cargo install --locked --version 0.5.14 cargo-hack
rustup install nightly
rustup target add --toolchain nightly wasm32-unknown-unknown
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
```

### What would you like to see?

Probably just some instructions in the `README.md` for now?

### What alternatives are there?

N/A

I can make a PR if this seems like the right approach.

**Comment by leighmcculloch** [comment]
I think we should change the default target that gets run by make so that it has less dependencies, because we mostly want developers focused on the individual examples, and we don't want/need them at this point in their experience to go through the process of installing these additional tools or nightly.
