### ISSUE TITLE
Add smart wallet example

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-examples#73]
### What problem does your feature solve?

Although smart wallets aren't widely used, they are a possible construction on Soroban and it would be good to know how they fit into the system.

### What would you like to see?

A simple smart wallet example. The most basic would be just an on-chain multi-signature configuration analogous to classic Stellar accounts.

### What alternatives are there?

N/A

**Comment by jonjove** [comment]
Another option would be to make a simple example similar to gnosis-safe that can take signatures asynchronously (eg. someone proposes a transaction and other signers confirm it). See https://docs.gnosis-safe.io/introduction/the-programmable-account/eoas-vs.-contract-accounts#multi-signature-wallets for context.

This is more complex, but has the nice feature of being something that cannot be done using classic Stellar accounts.

**Comment by tomerweller** [comment]
Another aspect of smart wallets that might be worth exploring is velocity controls. This also has the bonus of being not trivial in Stellar classic. 

A simple version is that there's a single admin signer with a fixed allowance per calendar day. More complex versions might include (1) combining with multisig for tiered limits based on number of signers. and/or (2) using sliding windows instead of calendar days

**Comment by smac711** [comment]
@jonjove @dmkozh are we actively working on this issue. If not and it is not critical or completion I will be moving it out of the 22.09.01 sprint to backlog.

**Comment by jonjove** [comment]
Yes #106 is open and will be merged in the next few days.

**Comment by smac711** [comment]
Hey @dmkozh are we ready to merge the above pull request in order to close off this issue?

**Comment by leighmcculloch** [comment]
I moved this into the Oct iteration and marked it as part of the Test & Polish steel thread. Anything in this repo is unlikely to classify as a code complete requirement.
